package com.nishenpeiris.surgicalsiteinfectionsurveillance.util;

/**
 * Represents an institute of referral
 *
 * @author Nishen Peiris
 */
public enum InstituteOfReferral {
    TEACHING_HOSPITAL_KANDY, TEACHING_HOSPITAL_PERADENIYA, OTHER_GENERAL_OR_TEACHING_HOSPITAL_WITHIN_CENTRAL_PROVINCE, OTHER_GENERAL_OR_TEACHING_HOSPITAL_OUTSIDE_CENTRAL_PROVINCE, DISTRICT_GENERAL_HOSPITAL_WITHIN_CENTRAL_PROVINCE, DISTRICT_GENERAL_HOSPITAL_OUTSIDE_CENTRAL_PROVINCE, PRIVATE_HEALTH_CARE_INSTITUTE_WITHIN_CENTRAL_PROVINCE, PRIVATE_HEALTH_CARE_HOSPITAL_OUTSIDE_CENTRAL_PROVINCE, OTHERS
}
