export const DISTRICTS: string[] = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticalloa',
  'Colombo',
  'Galle',
  'Gampaha',
  'Hambanthota',
  'Jafna',
  'Kaluthara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matale',
  'Matara',
  'Monaragala',
  'Mulathivu',
  'Nuwara Eliya',
  'Polonnaruwa',
  'Puttalam',
  'Rathnapura',
  'Trincomalee',
  'Vavuniya'
];
